### PR TITLE
git commit -M "swapped justify-content from space-between to center"

### PR DESCRIPTION
**Pull request by c-v-pop**
If I understood the problem 
image
The text started at the left of the page, I'm guessing you wanted it centered likewise. 
image

### CODE REVIEW

**Comment by 404mahdi** [comment]
No, I added a picture of the issue. Thank you.

image

**Comment by c-v-pop** [comment]
And isn't this the result wanted? 
image
It will stay centered all across devices now. 

At breakpoint 991px it changes to: 
image

**Comment by 404mahdi** [comment]
I didn't want it centered; I wanted it to be aligned with the title 'Aree Hi' in all screen sizes.

I know that centering the whole div will fix the problem, but it looks odd. I am also curious about what is causing that problem.

**Comment by c-v-pop** [comment]
@media (max-width: 1230px) {

    .hero {
        padding: 0 2em;
    }

}

This solution worked for me, are you happy with it?

**Review by 404mahdi — APPROVED** [review]
I think it's fine now. Thank you.

**Pull request merged**
